export type ThucDon = {
    nhomSanPhamId?: string,
    nhomSanPhamIdCha?: string,
    idToChuc?: string,
    nhomSanPhamSlug?: string,
    nhomSanPhamHinhAnh?: string,
    nhomSanPhamHoatDong?: boolean,
    nhomSanPhamTen?: string,
    nhomSanPhamMoTa?: string,
    nhomSanPhamIdNgonNgu?: string,
    sanPhamId?: string,
    dieuChinh?: number,
    giaDieuChinh?: number,
    giaNiemYet?: number,
    sanPhamHoatDong?: boolean,
    sanPhamMoTa?: string,
    sanPhamSlug?: string,
    sanPhamIdNgonNgu?: string,
    sanPhamTen?: string,
    sanPhamNoiDung?: string,
    sanPhamTrichDan?: string,
    loaiSanPhamId?: string,
    loaiSanPhamIdCha?: string,
    loaiSanPhamSlug?: string,
    loaiSanPhamIdNgonNgu?: string,
    loaiSanPhamTen?: string,
    loaiSanPhamMoTa?: string
}